gallery/urls.py
# Importar path desde django.urls
from django.urls import path, re_path
# importar .views
from .views import ArticleYearArchiveView, ArticleMonthArchiveView, ArticleDayArchiveView

# Importar vistas de app gallery
from . import views

app_name='gallery'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('blog/', views.blog_list, name='blog'),
    path('blog/tag/<slug:tag_slug>/', views.blog_list, name='gallery_list_by_tag'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:gallery>', views.blog_detail, name='blog_detail'),
    #path('blog/<int:year>/<int:month>/<int:day>', views.ArticleDayArchiveView.as_view(day_format='%d'), name='show_day'),
    #path('blog/<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name='show_month'),
    #path('blog/<int:year>/', views.ArticleYearArchiveView.as_view(), name='show_year'),    
    path('category/<str:url_clean>/', views.CategoryView, name='category'),
    path('contact/', views.contact, name='contact'),
]

gallery/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# importar taggit para el uso de tags valga la redundancia
from taggit.managers import TaggableManager
# importar django stdimage
from stdimage import StdImageField, JPEGField
# importar signals para eliminar las imagenes
from django.dispatch import receiver
# importar los settings
from django.conf import settings
# importar User
from django.contrib.auth.models import User
# importar slugify para convertir el texto de las url limpias en slug de manera automatica
from django.utils.text import slugify
# importar os para eliminar imagenes
import os


class Category(models.Model):
    """
    Creacion de categoría para las publicaciones
    """
    title = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    # definir modelo __str__
    def __str__(self):
        return self.title


class PublishedManager(models.Manager):
    """ 
    Custom manager para el modelo para las publicaciones de galeria
    que tengan el status de publicado ("published")
    """

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Gallery(models.Model):
    """ 
    Clase gallery donde se almacenaran las imagenes con sus descripciones
    """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_galleries")
    title = models.CharField(("Title"), max_length=150)
    # se actualiza el url_clean: url_clean = models.CharField(max_length=255),
    # no es necesario la migracion para actualizar
    url_clean = models.SlugField(("Url_Clean"), max_length=255, unique_for_date='publish')
    description = models.CharField(("Description"), max_length=255)
    body = models.TextField(("Body"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category_galleries")
    # Fecha de publicado, creado y actualizado
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # agregamos el tag para que el modelo sea etiquetable
    tags = TaggableManager()
    # status para ver si esta en borrador o publicado    
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # Campos Custom Manager
    # Manager por default
    objects = models.Manager()
    # Nuestro custom manager
    published = PublishedManager()

    # funcion save para setear el url_clean de manera automatica escribir blank=True
    """def save(self, *args, **kwargs):
        self.url_clean = slugify(self.title)
        super(Gallery, self).save(*args, **kwargs)"""

    class Meta:
        # Remove parent's ordering effect
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # Usar el URL de post detail para definir la construccion de una URL canonica
    # para los objectos post, para eso usaremos el metodo reverse(), que nos permite construir URLs
    # por su nombre y pasarle parametros opcionales
    def get_absolute_url(self):
        return reverse('gallery:blog_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.url_clean])


class Comment(models.Model):
    """ 
    Creacion del model de comentario para los posts
    """
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='comments')
    name =  models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Comentado por {self.name} en {self.post}'


class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    # image = models.ImageField(upload_to='images/')
    # image = models.JPEGField(upload_to='images/', variations={'custom': {'width': 800, 'height': 700, "crop": True}})
    image = StdImageField(upload_to='images/',variations={'custom': {'width': 800, 'height': 700, "crop": True}})
    # para obtener el nombre de la imagen original
    original_image_name = models.CharField(max_length=100, default='')
    # para obtener la extension
    original_image_ext = models.CharField(max_length=5, default='')

    def __str__(self):
        return self.title

    # guardar campos de manera personalizada
    def save(self, *args, **kwargs):
        """
            Obtener la referencia del nombre original de la imagen como de su extensión
        """
        (root, ext) = os.path.splitext(self.image.path)
        """
            Quitar path absoluto del archivo, para solo dejar la carpeta donde este
            se guardará (images), el nombre de la imagen y su extension.

            Importamos y llamamos a settings para quitar path absoluto 
            que yace en la variable root y solo dejar la carpeta donde se subirá(images).
            Esto es para almacenar el nombre y carpeta de nuestras imagenes en la base de datos
            elementimages -> original_image_name que es lo mismo que -> image, solo que esté sera llamado y el image no

            Condiciones:
                1. Si el original_image_name está vacío porque no hay imagen subida,
                   la variable root elimina el path absoluto y agrega la carpeta donde esta se sube (images)
                2. Si el original_image_name no está vacío, quiere decir que se está actualizando
                   ya sea la imagen o solo su titulo, en este caso hay dos posibilidades, asi que
                   necesitaremos primero comprobar si la variable root contiene la carpeta de subida (images), luego:
                   2.1. Si hayamos que la variable "palabra" se encuentra en la variable "root" quiere decir que
                        estamos actualizando solo el titulo de la imagen, por lo cual tendremos que quitar
                        todo el path absoluto y agregar "images/" nuevamente, de otro modo se nos duplicará en la BBDD,
                        asi que reemplazamos la palabra "images\" y luego eliminamos el path absoluto para que no se duplique
                   2.2 Sino encuentran la palabra en el root significa que estamos actualizando por otra imagen, entonces solo
                        procedemos a eliminar el path absoluto y agregar el nombre de la carpeta de subida "images/" y asignarla
                        nuevamente a original_image_name
        """
        if (self.original_image_name == ""):
            root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
            self.original_image_name = root
        elif (self.original_image_name != ""):
            # probar si root contene la palabra images\ para actualizar solo el titulo
            palabra = "images\\"
            if palabra in root.lower():
                root = root.replace('images\\', '')
                root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
                self.original_image_name = root
            else:
                root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
                self.original_image_name = root

        # guardar extensión de la imagen
        self.original_image_ext = ext

        # llamamos a la super clase para salvar datos
        super(GalleryImages, self).save(*args, **kwargs)


# Funcion para eliminar Imagenes Y sus CUSTOM al eliminar una imagen del registro en BBDD
# @receiver para estar atento cuando se borre para ser accionado
@receiver(models.signals.post_delete, sender=GalleryImages)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    # preguntar si la instancia (imagen original) existe
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

    # obtener el nombre original de la imagen como de su extensión (custom)
    (root, ext) = os.path.splitext(instance.image.path)

    # sumamos el nombre de la imagen original mas su extensión
    extra_file = root+".custom.jpg"

    # preguntar si la imagen custom existe para eliminarla
    if os.path.isfile(extra_file):
        os.remove(extra_file)


# Funcion para eliminar Imagenes al ser actualizarlas del registro en BBDD
# @receiver para estar atento cuando se borre para ser accionado
@receiver(models.signals.pre_save, sender=GalleryImages)
def auto_delete_file_on_update(sender, instance, **kwargs):

    # preguntar si tenemos pk
    if not instance.pk:
        return False

    # para buscar al elemento por su pk y por image
    try:
        old_file = GalleryImages.objects.get(pk=instance.pk).image
    except GalleryImages.DoesNotExist:
        return False

    # comparamos si tenemos una imagen antigua para eliminarla del registro
    new_file = instance.image
    if not old_file == new_file:
        # preguntar si la instancia antigua existe
        if instance.image:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

        # obtener el nombre original de la imagen como de su extensión (imagen custom)
        (root, ext) = os.path.splitext(old_file.path)

        # sumamos el nombre de la imagen original mas su extensión
        extra_old_file = root+".custom.jpg"

        # preguntar si la imagen custom existe para eliminarla
        if os.path.isfile(extra_old_file):
            os.remove(extra_old_file)


class Contact(models.Model):
    """
    Creacion del model de contacto
    """
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=80)

gallery/forms.py
# Crear formulario para crear un post en la galeria
from django import forms
from .models import Comment, Contact
from django.forms import Textarea, TextInput


class CommentForm(forms.ModelForm):
    """
    Clase para construir el formulario para los comentarios
    necesitaremos el forms.ModelForm para construir el form
    dinamicamente para el modelo Comment.
    """

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name' : TextInput(attrs={'class':'form-control'}),
            'email': TextInput(attrs={'class':'form-control'}),
            'body': Textarea(attrs={'class':'form-control'})
        }


class SearchForm(forms.Form):
    query = forms.CharField()


class ContactForm(forms.ModelForm):
    """ 
    Crear formulario de contacto
    """

    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')
        widgets = {
            'name' : TextInput(attrs={'class':'form-control', 'placeholder':'Tu Nombre'}),
            'email': TextInput(attrs={'class':'form-control', 'placeholder':'Tu Email'}),
            'subject': TextInput(attrs={'class':'form-control', 'placeholder':'Asunto'}),
            'message': Textarea(attrs={'class':'form-control', 'placeholder':'Mensaje', 'cols':'30', 'rows':'7'})
        }

gallery/templates/blog_detail.html
{% extends 'base.html' %}

{% load gallery_tags %}

{% block content %}

<section class="ftco-section ftco-bread">
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center">
	        <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Home</a></span> <span class="mr-2"><a href="{% url 'gallery:blog' %}">Blog</a></span> <span>{{ gallery.title }}</span></p>
	            <h1 class="bread">{{ gallery.title }}</h1>
	        </div>
	    </div>
	</div>
</section>
			
<section class="ftco-section">
	<div class="container">
	    <div class="row">
	    	<div class="col-lg-8 ftco-animate">
                {% for g in gallery.galleryimages_set.all|slice:"1" %}
                    <h2 class="mb-3 font-weight-bold">{{ g.title }}</h2>
                {% endfor %}
	            <p>{{ gallery.description }}</p>
	            <p>
                    {% for g in gallery.galleryimages_set.all %}
                        <img src="/uploads/{{ g.original_image_name |add:'.custom.jpg' }}" alt="{{ g.title }}" class="img-fluid">
                    {% endfor %}
	            </p>
	            <p>{{ gallery.body}}</p>
	        
	            <div class="tag-widget post-tag-container mb-5 mt-5">
	              	<div class="tagcloud">
						{% if gallery.tags.all.0 %}
							{% for tag in gallery.tags.all %}
								<a href="{% url 'gallery:gallery_list_by_tag' tag.slug %}" class="tag-cloud-link"> {{ tag.name }} </a>
							{% endfor %}
						{% endif %}
	              	</div>
	            </div>
	            
	            <div class="about-author d-flex p-4 bg-light">
	              <div class="bio mr-5">
	                <img src="images/person_1.jpg" alt="Image placeholder" class="img-fluid mb-4">
	              </div>
	              <div class="desc">
	                <h3>{{ gallery.author }}</h3>
	                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
	              </div>
	            </div>

	            <div class="pt-5 mt-5">
					{# Contar los comentarios #}
					{% with comments.count as total_comments %}
	              		<h3 class="mb-5 font-weight-bold">{{ total_comments }} Comentario{{ total_comments|pluralize }}</h3>
					{% endwith %}
					{# Listar los comentarios #}
	              	<ul class="comment-list">
					  	{# Realizar For #}
						{% for comment in comments %}
							<li class="comment">
								<div class="vcard bio">
									<img src="#" alt="Autor">
								</div>
								<div class="comment-body">
									<h3>{{ comment.name }}</h3>
									<div class="meta">{{ comment.created }}</div>
									<p>{{ comment.body|linebreaks }}</p>
									<p><a href="#" class="reply">Reply</a></p>
								</div>
							</li>	
						{% endfor %}
						{# Realizar For #}
	            	</ul>
	            	<!-- END comment-list -->
	            	{# Formulario para crear un comentario nuevo #}
					<div class="comment-form-wrap pt-5">
						<h3 class="mb-5">Deja un comentario</h3>
						<form method="post" class="p-3 p-md-5 bg-light">
							{#% for field in comment_form %#}
								<div class="form-group">
									<label for="name">Nombre *</label>
									{{ comment_form.name }}
									{# <input type="text" class="form-control" id="name"> #}
								</div>
								<div class="form-group">
									<label for="email">Email *</label>
									{{ comment_form.email }}
									{# <input type="email" class="form-control" id="email"> #}
								</div>
								<div class="form-group">
									<label for="message">Mensaje</label>
									{{ comment_form.body }}
									{# <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea> #}
								</div>
							{#% endfor %#}
							{% csrf_token %}
							<div class="form-group">
								<input type="submit" value="Publicar Comentario" class="btn py-3 px-4 btn-primary">
							</div>
						</form>
					</div>
	            </div>
	        </div> <!-- .col-md-8 -->
			<!-- .col-lg-4 -->
	    	{% include 'partials/column.html' %}
			<!-- end .col-lg-4 -->
	    </div>
	</div>
</section>

{% endblock content %}

gallery/templates/blog_list.html
{% extends 'base.html' %}

{% block content %}

<section class="ftco-section ftco-bread">
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center">
	        <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Inicio</a></span> <span>Blogs</span></p>
	            <h1 class="bread">Blogs</h1>
				{# Reemplazar breadcrumb y bread con blocks #}
	        </div>
	    </div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
	    <div class="row d-flex">
	    	<div class="col-lg-8">
	    		<div class="row">
					{# Aqui va el for #}
					{% for g in galleries %}
						<div class="col-md-12">
							<div class="blog-entry ftco-animate d-md-flex">
								<a href="{{ g.get_absolute_url }}" class="img img-2" style="background-image: url(/uploads/{{ g.galleryimages_set.all.0.original_image_name |add:'.custom.jpg' }});"></a>
								<div class="text text-2 p-4">
									<h3 class="mb-2"><a href="{{ g.get_absolute_url }}">{{ g.title }}</a></h3>
										<div class="meta-wrap">
											<p class="meta">
												<span>{{ g.created }}</span>
												<span><a href="{% url 'gallery:category' g.category.url_clean %}">{{ g.category }}</a></span>
												<span>5 Comment</span>
											</p>
										</div>
									<p class="mb-4">{{ g.description }}.</p>
									<p><a href="{{ g.get_absolute_url }}" class="btn-custom">Ir al Post <span class="ion-ios-arrow-forward"></span></a></p>
								</div>
							</div>
						</div>
					{% endfor %}
					{# Aqui termina el for #}
			    </div><!-- END-->
			    
				<div class="row">
			        <div class="col">
						{% include 'partials/pagination.html' with page_obj=galleries %}
			        </div>
			    </div>
			</div>
	    	
			{% include 'partials/column.html' %}

	    </div>
	</div>
</section>

{% endblock content %}

gallery/templates/blogger_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="ftco-section ftco-bread">
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center">
	        <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Inicio</a></span> <span>Blog</span></p>
	            <h1 class="bread">Archivos</h1>
	        </div>
	    </div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
	    <div class="row d-flex">
	    	<div class="col-lg-8">
	    		<div class="row">
					{# Aqui va el for #}
					
					{% for g in object_list %}
						<div class="col-md-12">
							<div class="blog-entry ftco-animate d-md-flex">
								<a href="{% url 'gallery:blog_detail' g.url_clean %}" class="img img-2" style="background-image: url('/uploads/{{ g.galleryimages_set.all.0.original_image_name |add:'.custom.jpg' }}') ;"></a>
								<div class="text text-2 p-4">
									<h3 class="mb-2"><a href="{% url 'gallery:blog_detail' g.url_clean %}">{{ g.title }}</a></h3>
										<div class="meta-wrap">
											<p class="meta">
												<span>{{ g.created }}</span>
												<span><a href="{% url 'gallery:category' g.category.url_clean %}">{{ g.category }}</a></span>
												<span>5 Comment</span>
											</p>
										</div>
									<p class="mb-4">{{ g.description }}.</p>
									<p><a href="{% url 'gallery:blog_detail' g.category.url_clean %}" class="btn-custom">Ir al Post <span class="ion-ios-arrow-forward"></span></a></p>
								</div>
							</div>
						</div>
					{% endfor %}
					{# Aqui termina el for #}
			    </div><!-- END-->
			    
				<div class="row">
			        <div class="col">
						{# incluir pagination #}
						{% include 'partials/pagination.html' %}
			        </div>
			    </div>
			</div>
	    	
			{% include 'partials/column.html' %}

	    </div>
	</div>
</section>

{% endblock content %}

gallery/templates/categories.html
{% extends 'base.html' %}

{% block content %}

<section class="ftco-section ftco-bread">
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center">
	        <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Inicio</a></span> <span>Categorias</span></p>
	            <h1 class="bread">{{ url_clean|title }}</h1>
	        </div>
	    </div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
	    <div class="row d-flex">
	    	<div class="col-lg-8">
	    		<div class="row">
					{# Aqui va el for #}
					{% for cate in category_posts %}
						<div class="col-md-12">
							<div class="blog-entry ftco-animate d-md-flex">
								<a href="{# url 'gallery:blog_detail' cate.url_clean #}" class="img img-2" style="background-image: url(/uploads/{{ cate.galleryimages_set.all.0.original_image_name |add:'.custom.jpg' }});"></a>
								<div class="text text-2 p-4">
									<h3 class="mb-2"><a href="{# url 'gallery:blog_detail' cate.url_clean #}">{# cate.title #}</a></h3>
										<div class="meta-wrap">
											<p class="meta">
												<span>{#{ cate.created #}</span>
												<span><a href="{# url 'gallery:category' cate.category.url_clean #}">{# cate.category #}</a></span>
												<span>5 Comment</span>
											</p>
										</div>
									<p class="mb-4">{# cate.description #}.</p>
									<p><a href="{# url 'gallery:blog_detail' cate.url_clean #}" class="btn-custom">Ir al Post <span class="ion-ios-arrow-forward"></span></a></p>
								</div>
							</div>
						</div>
					{% endfor %}
					{# Aqui termina el for #}
			    </div><!-- END-->
			    
				<div class="row">
			        <div class="col">
						{% include 'partials/pagination.html' with page_obj=category_posts %}
			        </div>
			    </div>
			</div>
	    	
			{% include 'partials/column.html' %}

	    </div>
	</div>
</section>

{% endblock content %}

gallery/templates/contact.html
{% extends 'base.html' %}

{% block content %}

<section class="ftco-section ftco-bread">
	<div class="container">
		<div class="row no-gutters slider-text justify-content-center align-items-center">
	        <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Inicio</a></span> <span>Contacto</span></p>
	            <h1 class="bread">Contacto</h1>
	        </div>
	    </div>
	</div>
</section>

<section class="ftco-section contact-section">
    <div class="container">
	    <div class="row d-flex mb-5 contact-info">
	        <div class="col-md-12 mb-4">
	            <h2 class="h3 font-weight-bold">Información de contacto</h2>
	        </div>
	        <div class="w-100"></div>
            <div class="col-md-3 d-flex">
                <div class="info bg-light p-4">
                    <p><span>Dirección:</span> Pasaje Andorra 1927, Maipú, Santiago, Chile</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-light p-4">
                    <p><span>Celular:</span> <a href="tel://56990911154">+ 569 90911154</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-light p-4">
                    <p><span>Email:</span> <a href="mailto:sergio.04.ramirez@gmail.com">sergio.04.ramirez@gmail.com</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="info bg-light p-4">
                    <p><span>LinkedIn</span> <a href="#">Sergio Ramírez</a></p>
                </div>
            </div>
	    </div>
	    <div class="row block-9">
            <div class="col-md-6 d-flex">
                <form method="post" class="bg-light p-5 contact-form">
                    {% csrf_token %}
                    
                    {% if contact_form.errors %}
                        {% for field in contact_form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ field.name }}:</strong> {{ error }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                        
                    <div class="form-group">
                        {{ contact_form.name }}
                    </div>
                    <div class="form-group">
                        {{ contact_form.email }}
                    </div>
                    <div class="form-group">
                        {{ contact_form.subject }}
                    </div>
                    <div class="form-group">
                        {{ contact_form.message }}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Enviar Mensaje" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
            </div>
            <div class="col-md-6 d-flex">
                {# <div id="map" class="bg-light"></div> #}
            </div>
	    </div>
	</div>
</section>

{% endblock content %}

gallery/templates/gallery.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
	<section class="ftco-section ftco-bread">
		<div class="container">
			<div class="row no-gutters slider-text justify-content-center align-items-center">
				<div class="col-md-8 ftco-animate">
					<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'gallery:index' %}">Inicio</a></span><span>Galería</span></p>
					<h1 class="bread">Galería</h1>
				</div>
			</div>
		</div>
	</section>
	<section class="ftco-section-3">
		<div class="photograhy">
			<div class="row">
				{# Agarrar este para hacer el if #}
				{% for g in gallery %}
					<div class="col-md-4 ftco-animate">
						{# Comprobar si la imagen asociada existe #}
						<a 	
							href="
								{% if g.galleryimages_set.all.count %}
									/uploads/{{ g.galleryimages_set.all.0.original_image_name |add:'.custom.jpg' }}
								{% else %}
									/uploads/images/default-image.jpg
								{% endif %}" 
							class="photography-entry img image-popup d-flex justify-content-start align-items-end" 
							style="background-image: url(/uploads/{{ g.galleryimages_set.all.0.original_image_name |add:'.custom.jpg' }});">
							<div class="overlay"></div>
							<div class="text ml-4 mb-4">
								<h3>{{ g.title }}</h3>
								{# Llamar a la categoria en este caso retorna el titulo #}
								{# esta consumiento muchas querys #}
								<span class="tag">{{ g.category }}</span>
							</div>
						</a>
						
					</div>

				{% endfor %}

				{# Fin agarrar #}
			</div>
		</div>

		{# Incluir paginacion #}
		<div class="pagination justify-content-center">
			{% include 'partials/pagination.html' with page_obj=gallery %}
		</div>

	</section>

	

{% endblock content%}

gallery/templates/latest_galleries.html
{% for gallery in latest_galleries %}
    <li>
        <a href="{{ gallery.get_absolute_url }}" class="img" 
        style="background-image: url(
        {% if gallery.galleryimages_set.all.count %}
            /uploads/{{ gallery.galleryimages_set.all.0.image}}
        {% else %}
            /uploads/images/default-image.jpg
        {% endif %}
        );"></a>
    </li>
{% endfor %}

{# for g in gallery_images|slice:"6" #}
                        