chillAmbientalist/urls.py
# Django modules
from django.contrib import admin
# importar i18n_patterns (libro chapter 3)
from django.conf.urls.i18n import i18n_patterns
# añadir include
from django.urls import path, include
# importar settings y static para que funcione el añadir static
from django.conf import settings
from django.conf.urls.static import static
# importar redirect (libro chapter 3)
from django.shortcuts import redirect

app_name = 'chillAmbientalist'

urlpatterns = [
    path('admin/', admin.site.urls),
    # Path de templates/partials/index.html
    path('', include('gallery.urls')),
]

"""
url_patterns += static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)
urlpatterns += static("/uploads/", document_root=settings.MEDIA_ROOT)
"""

# ignorar aviso del VS
# IMPORTANTE

""" in urls.py
urlpatterns = [
    .....
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)"""

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static("/uploads/", document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

gallery/urls.py
# Importar path desde django.urls
from django.urls import path, re_path
# importar .views
from .views import ArticleYearArchiveView, ArticleMonthArchiveView, ArticleDayArchiveView

# Importar vistas de app gallery
from . import views

app_name='gallery'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('blog/', views.blog_list, name='blog'),
    path('blog/tag/<slug:tag_slug>/', views.blog_list, name='gallery_list_by_tag'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:gallery>', views.blog_detail, name='blog_detail'),
    #path('blog/<int:year>/<int:month>/<int:day>', views.ArticleDayArchiveView.as_view(day_format='%d'), name='show_day'),
    #path('blog/<int:year>/<int:month>/', views.ArticleMonthArchiveView.as_view(month_format='%m'), name='show_month'),
    #path('blog/<int:year>/', views.ArticleYearArchiveView.as_view(), name='show_year'),    
    path('category/<str:url_clean>/', views.CategoryView, name='category'),
    path('contact/', views.contact, name='contact'),
]

gallery/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# importar taggit para el uso de tags valga la redundancia
from taggit.managers import TaggableManager
# importar django stdimage
from stdimage import StdImageField, JPEGField
# importar signals para eliminar las imagenes
from django.dispatch import receiver
# importar los settings
from django.conf import settings
# importar User
from django.contrib.auth.models import User
# importar slugify para convertir el texto de las url limpias en slug de manera automatica
from django.utils.text import slugify
# importar os para eliminar imagenes
import os


class Category(models.Model):
    """
    Creacion de categoría para las publicaciones
    """
    title = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255)

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    # definir modelo __str__
    def __str__(self):
        return self.title


class PublishedManager(models.Manager):
    """ 
    Custom manager para el modelo para las publicaciones de galeria
    que tengan el status de publicado ("published")
    """

    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Gallery(models.Model):
    """ 
    Clase gallery donde se almacenaran las imagenes con sus descripciones
    """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_galleries")
    title = models.CharField(("Title"), max_length=150)
    # se actualiza el url_clean: url_clean = models.CharField(max_length=255),
    # no es necesario la migracion para actualizar
    url_clean = models.SlugField(("Url_Clean"), max_length=255, unique_for_date='publish')
    description = models.CharField(("Description"), max_length=255)
    body = models.TextField(("Body"))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category_galleries")
    # Fecha de publicado, creado y actualizado
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # agregamos el tag para que el modelo sea etiquetable
    tags = TaggableManager()
    # status para ver si esta en borrador o publicado    
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # Campos Custom Manager
    # Manager por default
    objects = models.Manager()
    # Nuestro custom manager
    published = PublishedManager()

    # funcion save para setear el url_clean de manera automatica escribir blank=True
    """def save(self, *args, **kwargs):
        self.url_clean = slugify(self.title)
        super(Gallery, self).save(*args, **kwargs)"""

    class Meta:
        # Remove parent's ordering effect
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # Usar el URL de post detail para definir la construccion de una URL canonica
    # para los objectos post, para eso usaremos el metodo reverse(), que nos permite construir URLs
    # por su nombre y pasarle parametros opcionales
    def get_absolute_url(self):
        return reverse('gallery:blog_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.url_clean])


class Comment(models.Model):
    """ 
    Creacion del model de comentario para los posts
    """
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='comments')
    name =  models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Comentado por {self.name} en {self.post}'


class GalleryImages(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    # image = models.ImageField(upload_to='images/')
    # image = models.JPEGField(upload_to='images/', variations={'custom': {'width': 800, 'height': 700, "crop": True}})
    image = StdImageField(upload_to='images/',variations={'custom': {'width': 800, 'height': 700, "crop": True}})
    # para obtener el nombre de la imagen original
    original_image_name = models.CharField(max_length=100, default='')
    # para obtener la extension
    original_image_ext = models.CharField(max_length=5, default='')

    def __str__(self):
        return self.title

    # guardar campos de manera personalizada
    def save(self, *args, **kwargs):
        """
            Obtener la referencia del nombre original de la imagen como de su extensión
        """
        (root, ext) = os.path.splitext(self.image.path)
        """
            Quitar path absoluto del archivo, para solo dejar la carpeta donde este
            se guardará (images), el nombre de la imagen y su extension.

            Importamos y llamamos a settings para quitar path absoluto 
            que yace en la variable root y solo dejar la carpeta donde se subirá(images).
            Esto es para almacenar el nombre y carpeta de nuestras imagenes en la base de datos
            elementimages -> original_image_name que es lo mismo que -> image, solo que esté sera llamado y el image no

            Condiciones:
                1. Si el original_image_name está vacío porque no hay imagen subida,
                   la variable root elimina el path absoluto y agrega la carpeta donde esta se sube (images)
                2. Si el original_image_name no está vacío, quiere decir que se está actualizando
                   ya sea la imagen o solo su titulo, en este caso hay dos posibilidades, asi que
                   necesitaremos primero comprobar si la variable root contiene la carpeta de subida (images), luego:
                   2.1. Si hayamos que la variable "palabra" se encuentra en la variable "root" quiere decir que
                        estamos actualizando solo el titulo de la imagen, por lo cual tendremos que quitar
                        todo el path absoluto y agregar "images/" nuevamente, de otro modo se nos duplicará en la BBDD,
                        asi que reemplazamos la palabra "images\" y luego eliminamos el path absoluto para que no se duplique
                   2.2 Sino encuentran la palabra en el root significa que estamos actualizando por otra imagen, entonces solo
                        procedemos a eliminar el path absoluto y agregar el nombre de la carpeta de subida "images/" y asignarla
                        nuevamente a original_image_name
        """
        if (self.original_image_name == ""):
            root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
            self.original_image_name = root
        elif (self.original_image_name != ""):
            # probar si root contene la palabra images\ para actualizar solo el titulo
            palabra = "images\\"
            if palabra in root.lower():
                root = root.replace('images\\', '')
                root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
                self.original_image_name = root
            else:
                root = root.replace(settings.MEDIA_ROOT+"\\", "images/")
                self.original_image_name = root

        # guardar extensión de la imagen
        self.original_image_ext = ext

        # llamamos a la super clase para salvar datos
        super(GalleryImages, self).save(*args, **kwargs)


# Funcion para eliminar Imagenes Y sus CUSTOM al eliminar una imagen del registro en BBDD
# @receiver para estar atento cuando se borre para ser accionado
@receiver(models.signals.post_delete, sender=GalleryImages)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    # preguntar si la instancia (imagen original) existe
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

    # obtener el nombre original de la imagen como de su extensión (custom)
    (root, ext) = os.path.splitext(instance.image.path)

    # sumamos el nombre de la imagen original mas su extensión
    extra_file = root+".custom.jpg"

    # preguntar si la imagen custom existe para eliminarla
    if os.path.isfile(extra_file):
        os.remove(extra_file)


# Funcion para eliminar Imagenes al ser actualizarlas del registro en BBDD
# @receiver para estar atento cuando se borre para ser accionado
@receiver(models.signals.pre_save, sender=GalleryImages)
def auto_delete_file_on_update(sender, instance, **kwargs):

    # preguntar si tenemos pk
    if not instance.pk:
        return False

    # para buscar al elemento por su pk y por image
    try:
        old_file = GalleryImages.objects.get(pk=instance.pk).image
    except GalleryImages.DoesNotExist:
        return False

    # comparamos si tenemos una imagen antigua para eliminarla del registro
    new_file = instance.image
    if not old_file == new_file:
        # preguntar si la instancia antigua existe
        if instance.image:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

        # obtener el nombre original de la imagen como de su extensión (imagen custom)
        (root, ext) = os.path.splitext(old_file.path)

        # sumamos el nombre de la imagen original mas su extensión
        extra_old_file = root+".custom.jpg"

        # preguntar si la imagen custom existe para eliminarla
        if os.path.isfile(extra_old_file):
            os.remove(extra_old_file)


class Contact(models.Model):
    """
    Creacion del model de contacto
    """
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=80)

chillAmbientalist/apps/core/views.py
from django.shortcuts import render

# Create your views here.

chillAmbientalist/templates/partials/aside.html
{# Cargar static #}
{% load static %}

<aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
    <h1 id="colorlib-logo">
        <a href="{% url 'gallery:index' %}">
            <span class="img" style="background-image: url({% static 'site/images/author.jpg' %});"></span>Chill Ambient
        </a>
    </h1>
    <nav id="colorlib-main-menu" role="navigation">
        <ul>
            <li class="{% if request.resolver_match.url_name == 'index' %} colorlib-active {% endif %}"><a href="{% url 'gallery:index' %}">Inicio</a></li>
            <li class="{% if request.resolver_match.url_name == 'gallery' %} colorlib-active {% endif %}"><a href="{% url 'gallery:gallery' %}">Galería</a></li>
            <li class="{% if request.resolver_match.url_name == 'blog' %} colorlib-active {% endif %}"><a href="{% url 'gallery:blog' %}">Blogs</a></li>
            <li class="{% if request.resolver_match.url_name == 'about' %} colorlib-active {% endif %}"><a href="{% url 'gallery:about' %}">Acerca de mí</a></li>
            <li class="{% if request.resolver_match.url_name == 'services' %} colorlib-active {% endif %}"><a href="{% url 'gallery:services' %}">Mis Servicios</a></li>
            <li class="{% if request.resolver_match.url_name == 'contact' %} colorlib-active {% endif %}"><a href="{% url 'gallery:contact' %}">Contacto</a></li>
        </ul>
    </nav>
    <div class="colorlib-footer">
        <h3>Chechon's Blog</h3>
        <div class="d-flex justify-content-center">
            <p>Modo Depuración</p>
        </div>
    </div>
</aside>

chillAmbientalist/templates/partials/column.html
{% load static %}
{% load gallery_tags %}

<div class="col-lg-4 sidebar ftco-animate bg-light">
    <div class="sidebar-box">
        <form action="#" class="search-form">
            <div class="form-group">
                <span class="icon icon-search"></span>
                <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
        </form>
    </div>

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Categorias</h3>
        <ul class="categories">
            {# for para las categorias #}
            {% for c in categories|slice:"5" %}
                <li><a href="{% url 'gallery:category' c.url_clean %}">{{ c.title|capfirst }} <span> {{ c.list.0 |length }} </span></a></li>
            {% endfor %}
        </ul>
    </div>

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Blogs Populares</h3>
        {# hacer el for aquí o llamar un custom tag #}
            {% get_most_commented_galleries as most_commented_galleries %}
            {% for gallery in most_commented_galleries %}
                <div class="block-21 mb-4 d-flex">
                    <a class="blog-img mr-4" style="background-image: url(
                                                    {% if gallery.galleryimages_set.all.count %}
                                                        /uploads/{{ gallery.galleryimages_set.all.0.image}}
                                                    {% else %}
                                                        /uploads/images/default-image.jpg
                                                    {% endif %}
                                                    );"></a>
                    <div class="text">
                        <h3 class="heading"><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></h3>
                        <div class="meta">
                            <div><a href="{{ gallery.get_absolute_url }}"><span class="icon-calendar"></span> {{ gallery.publish|date:"d F Y" }}</a></div>
                            <div><a href="{{ gallery.get_absolute_url }}"><span class="icon-person"></span> {{ gallery.author }}</a></div>
                            <div><a href="{{ gallery.get_absolute_url }}"><span class="icon-chat"></span> 0</a></div>
                            {# hacer un count en gallery_tag para los comentarios #}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {# fin for #}
    </div>

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Tags</h3>
        <ul class="tagcloud">
            {# realizar for #}	
            {% for t in tags|slice:"8" %}
                <a href="#" class="tag-cloud-link">{{t.name}}</a>
            {% endfor %}
        </ul>
    </div>

    <div class="sidebar-box subs-wrap img" style="background-image: url(images/bg_1.jpg);">
        <div class="overlay"></div>
        <h3 class="mb-4 sidebar-heading">Anuncios</h3>
        <p class="mb-4">Estamos en modo desarrollo, seguimos añadiendo funcionalidades para el proyecto!</p>
    </div>

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Archivos</h3>
        <ul class="categories">
            {# Cargar categorias #}
            {% regroup gallery_images by created.year as year_list %}
            {% for year in year_list|slice:"6" %}
                {% regroup year.list by created.month as month_list %}
                    {% for month in month_list %}
                        <li><a href="{% url 'gallery:blog'%}{{year.grouper}}/{{month.grouper}}/">{{ month.list.0.created|date:'F Y' }} <span>({{ month.list|length }})</span></a></li>
                    {% endfor %}
            {% endfor %}
            {# Fin cargar categorias #}
        </ul>
    </div>

    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Beta</h3>
        <p>Este es un proyecto de prueba, todo los datos pueden ser susceptibles a cambios, al igual que colores entre otros.</p>
    </div>
</div><!-- END COL -->

chillAmbientalist/templates/partials/footer.html
{% load static %}
{% load gallery_tags %}

<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container px-md-5">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Publicaciones Recientes</h2>
                    <ul class="list-unstyled photo">
                        {% show_latest_posts 6 %}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Últimos Archivos</h2>
                    <ul class="list-unstyled categories">
                        {# Cargar categorias #}
                        {% regroup gallery_images by created.year as year_list %}
                        {% for year in year_list|slice:"2" %}
                            {% regroup year.list by created.month as month_list %}
                                {% for month in month_list %}
                                    <li><a href="{% url 'gallery:blog'%}{{year.grouper}}/{{month.grouper}}/">{{ month.list.0.created|date:'F Y' }} <span>({{ month.list|length }})</span></a></li>
                                {% endfor %}
                        {% endfor %}
                        {# Fin cargar categorias #}
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">¿Tienes dudas?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">Andorra 1927,
                                    Maipú, Santiago, Chile</span></li><br>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+(569) 90911154</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span
                                        class="text">sergio.04.ramirez@gmail.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is
                    made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                        target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

chillAmbientalist/templates/partials/pagination.html
{# Codigo de pagination django topic paginations#}    

{# <nav aria-label="Page navigation example"> #}
<div class="block-27">
    <ul>
        {% comment %}
            <li class="page-item disabled">
                <a href="#">
                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                </a>
            </li>
        {% endcomment %}    

        {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}"> &lt; </a>
            </li>
        {% comment %}
            {% else %}
            <li class="disabled">
                <a href="#"> &lt; </a>
            </li>
        {% endcomment %}
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            
            {% if i == page_obj.number %}
                <li class="active">
                    <a href="#">{{ i }}</a>
                </li>
            {% else %}
                <li>
                    <a href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
            
        {% endfor %}

        {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}"> &gt; </a>
            </li>
            {% comment %}
                {% else %}
                    <li class="disabled">
                        <a href="#"> &gt; </a>
                    </li>
            {% endcomment %}
        {% endif %}

    </ul>
</div>        
{# </nav> #}